In [1]:
import tensorflow as tf

In [2]:
v = tf.constant(2)

In [3]:
m = tf.constant(4)

In [8]:
k = tf.add(v,m )

In [9]:
k

<tf.Tensor: shape=(), dtype=int32, numpy=6>

In [10]:
Matrix_one = tf.constant([[2,3],
                          [3,4]])
Matrix_two = tf.constant([[2,3],
                          [3,4]])

@tf.function
def mathmul():
  return tf.matmul(Matrix_one, Matrix_two)


mul_operation = mathmul()

print ("Defined using tensorflow function :")
print(mul_operation)

Defined using tensorflow function :
tf.Tensor(
[[13 18]
 [18 25]], shape=(2, 2), dtype=int32)


In [11]:
r = tf.constant([4])
p = tf.constant([7])


In [12]:
tf.add(r,p)

<tf.Tensor: shape=(1,), dtype=int32, numpy=array([11], dtype=int32)>